require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'


target 'Goma' do
  config = use_native_modules!

  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  
  # pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  # pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'
  
  target 'OneSignalNotificationServiceExtension' do
    pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
  end
  
  target 'GomaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
      react_native_post_install(installer)
      # __apply_Xcode_12_5_M1_post_install_workaround(installer)
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
        end
      end

    end
  # post_install do |installer|
  #   react_native_post_install(installer)
  # end
end




